### PR TITLE
Appbar

### PR DESCRIPTION
**Pull request by erin-smith**
Initial Appbar design with dropdown menu- still needs Avatar/score from DB store and correct image background

### CODE REVIEW

**Comment by reptile18** [comment]
Did we decide on using a different icon for the appbar?
image

**Comment by reptile18** [comment]
we're creating this primarily for mobile, so the mobile view should be the one we make sure looks good:
image

**Comment by reptile18** [comment]
the score looks to be working just fine...
image

**Comment by erin-smith** [comment]
> Did we decide on using a different icon for the appbar?
> I can't remember which one....

   I can change it... still trying to figure out the background stone image.  I think I got the avatar to work, and trying to fix my linter

**Comment by alexastef** [comment]
really like the font! let us know when it's ready for review. If the background image is too much of a hassle or makes it difficult to read, we can always just make it a more custom color instead of the blue.

**Review by reptile18 — APPROVED** [review]

**Pull request merged**
